server:
  port: 8082

rocksdb:
  data-dir: block-data/node2

tio:
  heart-timeout: 5000
  client-group-name: ppblock-client
  server-group-context-name: ppblock-server
  server-port: 6789
  server-ip: 127.0.0.1
  nodes:
    -
      ip: 127.0.0.1
      port: 5678
    -
      ip: 127.0.0.1
      port: 7890
